'use client';
import { useEffect, useMemo, useState } from 'react';

type Connection={id:string;provider:string;name?:string;status:string;updatedAt:string;config?:Record<string,unknown>};
type Event={id:string;provider:string;entity:string;operation:string;source:string;status:string;receivedAt:string;error?:string};
type Conflict={id:string;entity:string;field:string;localValue:unknown;remoteValue:unknown;status:string;detectedAt:string};
const api=async(path:string,init?:RequestInit)=>{const r=await fetch(`/api/sc/${path}`,{...init,headers:{'content-type':'application/json',...(init?.headers??{})}});const b=await r.json();if(!r.ok)throw new Error(b.message??'Request failed');return b;};
export default function Page(){
  const [connections,setConnections]=useState<Connection[]>([]);const [events,setEvents]=useState<Event[]>([]);const [conflicts,setConflicts]=useState<Conflict[]>([]);const [provider,setProvider]=useState('hubspot');const [name,setName]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const active=useMemo(()=>connections.filter(c=>c.status==='active').length,[connections]);
  async function load(){try{setError('');const [c,e,f]=await Promise.all([api('connections'),api('events?limit=50'),api('conflicts?status=open')]);setConnections(c.connections);setEvents(e.events);setConflicts(f.conflicts);}catch(e){setError(e instanceof Error?e.message:String(e));}}
  useEffect(()=>{void load();const id=setInterval(()=>void load(),10000);return()=>clearInterval(id)},[]);
  async function create(){setBusy(true);try{const c=await api('connections',{method:'POST',body:JSON.stringify({provider,name:name||undefined})});const auth=await api(`connections/${c.id}/authorize`,{method:'POST'});location.href=auth.url;}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}}
  async function action(id:string,kind:'pause'|'resume'){await api(`connections/${id}/${kind}`,{method:'POST'});await load();}
  async function sync(id:string,entity:string,kind:'backfill'|'reconcile'){await api(`connections/${id}/sync/${entity}/${kind}`,{method:'POST'});await load();}
  async function resolve(id:string,choice:'local'|'remote'|'ignore'){await api(`conflicts/${id}/resolve`,{method:'POST',body:JSON.stringify({choice})});await load();}
  return <main>
    <header><div><span className="eyebrow">OPEN SOURCE CRM SYNC</span><h1>Sales-Connect</h1><p>Bidirectional Salesforce, HubSpot and Zoho synchronization control plane.</p></div><button className="ghost" onClick={()=>void load()}>Refresh</button></header>
    {error&&<div className="error">{error}</div>}
    <section className="stats"><article><b>{connections.length}</b><span>Connections</span></article><article><b>{active}</b><span>Active</span></article><article><b>{events.filter(e=>e.status==='failed').length}</b><span>Failed events</span></article><article><b>{conflicts.length}</b><span>Open conflicts</span></article></section>
    <section className="panel"><div className="panelTitle"><div><h2>Connect a CRM</h2><p>OAuth credentials stay on the Sales-Connect server.</p></div></div><div className="form"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="salesforce">Salesforce</option><option value="hubspot">HubSpot</option><option value="zoho">Zoho CRM</option></select><input placeholder="Connection name" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} onClick={()=>void create()}>{busy?'Starting…':'Connect'}</button></div></section>
    <section className="panel"><div className="panelTitle"><h2>Connections</h2><span>{connections.length}</span></div><div className="grid">{connections.map(c=><article className="card" key={c.id}><div className="row"><strong>{c.name||c.provider}</strong><span className={`badge ${c.status}`}>{c.status}</span></div><p>{c.provider} · {c.id.slice(0,18)}…</p><div className="actions"><button className="small" onClick={()=>void action(c.id,c.status==='paused'?'resume':'pause')}>{c.status==='paused'?'Resume':'Pause'}</button><button className="small" onClick={()=>void sync(c.id,'contact','reconcile')}>Reconcile contacts</button><button className="small" onClick={()=>void sync(c.id,'contact','backfill')}>Backfill</button></div></article>)}</div></section>
    <section className="two"><div className="panel"><div className="panelTitle"><h2>Recent events</h2><span>{events.length}</span></div><div className="table">{events.map(e=><div className="tr" key={e.id}><div><strong>{e.entity}.{e.operation}</strong><small>{e.provider} · {e.source}</small></div><span className={`badge ${e.status}`}>{e.status}</span></div>)}</div></div><div className="panel"><div className="panelTitle"><h2>Conflicts</h2><span>{conflicts.length}</span></div><div className="table">{conflicts.length===0&&<p className="empty">No open conflicts.</p>}{conflicts.map(c=><div className="conflict" key={c.id}><strong>{c.entity}.{c.field}</strong><small>Local: {JSON.stringify(c.localValue)}</small><small>Remote: {JSON.stringify(c.remoteValue)}</small><div className="actions"><button className="small" onClick={()=>void resolve(c.id,'local')}>Use local</button><button className="small" onClick={()=>void resolve(c.id,'remote')}>Use remote</button><button className="small" onClick={()=>void resolve(c.id,'ignore')}>Ignore</button></div></div>)}</div></div></section>
  </main>
}
