import { createHmac, timingSafeEqual } from 'node:crypto';
import type { CRMProvider, EntitySyncConfig, FieldSchema, ListOptions, ListPage, OAuthConfig, ObjectSchema, ProviderRequestContext, ProviderWebhookEvent, RemoteRecord, TokenSet } from '@sales-connect/types';
import { fetchJson, genericDenormalize, genericNormalize } from '@sales-connect/provider-common';

export class HubSpotProvider implements CRMProvider {
  id='hubspot' as const;
  capabilities(){return {webhooks:true,cdc:false,upsert:true,externalIds:true,customObjects:true,batchWrite:true,bulkRead:false};}
  getAuthorizationUrl(c:OAuthConfig,state:string,scopes:string[]=[]){ const q=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,scope:scopes.join(' '),state}); return `https://app.hubspot.com/oauth/authorize?${q}`; }
  async exchangeAuthorizationCode(c:OAuthConfig,code:string){ const form=new URLSearchParams({grant_type:'authorization_code',client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,code}); const b=await fetchJson<any>('https://api.hubapi.com/oauth/v3/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}); return this.token(b); }
  async refreshToken(c:OAuthConfig,t:TokenSet){ if(!t.refreshToken)throw new Error('HubSpot refresh token missing'); const form=new URLSearchParams({grant_type:'refresh_token',client_id:c.clientId,client_secret:c.clientSecret,refresh_token:t.refreshToken}); const b=await fetchJson<any>('https://api.hubapi.com/oauth/v3/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}); return {...t,...this.token(b),refreshToken:b.refresh_token??t.refreshToken}; }
  private token(b:any):TokenSet{return {accessToken:b.access_token,refreshToken:b.refresh_token,tokenType:b.token_type??'Bearer',scope:b.scope,expiresAt:Date.now()+Number(b.expires_in??1800)*1000};}
  private headers(ctx:ProviderRequestContext){return {authorization:`Bearer ${ctx.credentials.accessToken}`,'content-type':'application/json'};}
  async discoverObjects(_ctx:ProviderRequestContext){return ['contacts','companies','deals','tickets'].map(name=>({name,label:name,fields:[]} satisfies ObjectSchema));}
  async discoverFields(ctx:ProviderRequestContext,object:string){ const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/properties/${encodeURIComponent(object)}`,{headers:this.headers(ctx)}); return (b.results??[]).map((f:any)=>({name:f.name,label:f.label,type:f.type,readable:true,writable:!f.modificationMetadata?.readOnlyValue,required:false,unique:f.hasUniqueValue} satisfies FieldSchema)); }
  async getRecord(ctx:ProviderRequestContext,object:string,id:string,fields?:string[]){ const q=fields?.length?`?properties=${encodeURIComponent(fields.join(','))}`:''; const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}/${encodeURIComponent(id)}${q}`,{headers:this.headers(ctx)}); return this.remote(object,b); }
  async listRecords(ctx:ProviderRequestContext,object:string,options:ListOptions={}):Promise<ListPage>{
    if(options.modifiedSince){ const filters=[{propertyName:'hs_lastmodifieddate',operator:'GTE',value:String(Date.parse(options.modifiedSince))}]; const body:any={filterGroups:[{filters}],sorts:['hs_lastmodifieddate'],limit:Math.min(options.limit??200,200),properties:options.fields??[]}; if(options.cursor)body.after=options.cursor; const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}/search`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify(body)}); return {records:(b.results??[]).map((r:any)=>this.remote(object,r)),nextCursor:b.paging?.next?.after,watermark:new Date().toISOString()}; }
    const q=new URLSearchParams({limit:String(Math.min(options.limit??100,100))}); if(options.cursor)q.set('after',options.cursor); if(options.fields?.length)q.set('properties',options.fields.join(',')); const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}?${q}`,{headers:this.headers(ctx)}); return {records:(b.results??[]).map((r:any)=>this.remote(object,r)),nextCursor:b.paging?.next?.after,watermark:new Date().toISOString()};
  }
  async createRecord(ctx:ProviderRequestContext,object:string,data:Record<string,unknown>){ const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify({properties:data})}); return this.remote(object,b); }
  async updateRecord(ctx:ProviderRequestContext,object:string,id:string,data:Record<string,unknown>){ const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}/${encodeURIComponent(id)}`,{method:'PATCH',headers:this.headers(ctx),body:JSON.stringify({properties:data})}); return this.remote(object,b); }
  async upsertRecord(ctx:ProviderRequestContext,object:string,key:{field:string;value:string},data:Record<string,unknown>){ const b=await fetchJson<any>(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}/batch/upsert`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify({inputs:[{id:key.value,idProperty:key.field,properties:data}]})}); const r=b.results?.[0]; if(!r?.id)throw new Error('HubSpot upsert returned no record'); return this.remote(object,r); }
  async deleteRecord(ctx:ProviderRequestContext,object:string,id:string){ const res=await fetch(`https://api.hubapi.com/crm/v3/objects/${encodeURIComponent(object)}/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers(ctx)}); if(!res.ok&&res.status!==404)throw new Error(`HubSpot archive failed: ${res.status}`); }
  normalize(object:string,remote:RemoteRecord,mapping:EntitySyncConfig){return genericNormalize(object,remote,mapping);}
  denormalize(object:string,canonical:any,mapping:EntitySyncConfig){return genericDenormalize(object,canonical,mapping);}
  verifyWebhook(args:{headers:Record<string,string|string[]|undefined>;method:string;url:string;rawBody:string;secret:string}){ const sig=String(args.headers['x-hubspot-signature-v3']??''); const ts=String(args.headers['x-hubspot-request-timestamp']??''); if(!sig||!ts||Math.abs(Date.now()-Number(ts))>300000)return false; let uri=args.url; try{uri=decodeURIComponent(uri);}catch{} const expected=createHmac('sha256',args.secret).update(`${args.method}${uri}${args.rawBody}${ts}`).digest('base64'); const a=Buffer.from(sig);const b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b); }
  async parseWebhook(payload:unknown):Promise<ProviderWebhookEvent[]>{ const arr=Array.isArray(payload)?payload:[]; return arr.map((e:any)=>{ const kind=String(e.subscriptionType??'contact.change').split('.')[0]; const object=kind==='company'?'companies':kind==='deal'?'deals':kind==='ticket'?'tickets':'contacts'; const type=String(e.subscriptionType??''); const operation=type.includes('deletion')?'delete':type.includes('creation')?'create':'update'; return {id:String(e.eventId??`${e.objectId}:${e.occurredAt}:${type}`),object,remoteId:String(e.objectId),operation,occurredAt:e.occurredAt?new Date(e.occurredAt).toISOString():undefined,changedFields:e.propertyName?[e.propertyName]:undefined,payload:e}; }); }
  private remote(object:string,b:any):RemoteRecord{return {id:String(b.id),object,fields:b.properties??{},createdAt:b.createdAt,updatedAt:b.updatedAt,deleted:b.archived,raw:b};}
}
