import type { CRMProvider, EntitySyncConfig, FieldSchema, ListOptions, ListPage, OAuthConfig, ObjectSchema, ProviderRequestContext, ProviderWebhookEvent, RemoteRecord, TokenSet } from '@sales-connect/types';
import { assertIdentifier, fetchJson, genericDenormalize, genericNormalize } from '@sales-connect/provider-common';

export interface ZohoProviderOptions { accountsUrl?:string; apiDomain?:string }
export class ZohoProvider implements CRMProvider {
  id='zoho' as const; private accountsUrl:string;private apiDomain:string;
  constructor(o:ZohoProviderOptions={}){this.accountsUrl=o.accountsUrl??'https://accounts.zoho.com';this.apiDomain=o.apiDomain??'https://www.zohoapis.com';}
  capabilities(){return {webhooks:true,cdc:false,upsert:true,externalIds:true,customObjects:true,batchWrite:true,bulkRead:true};}
  getAuthorizationUrl(c:OAuthConfig,state:string,scopes:string[]=[]){const q=new URLSearchParams({scope:scopes.join(','),client_id:c.clientId,response_type:'code',access_type:'offline',redirect_uri:c.redirectUri,state,prompt:'consent'});return `${this.accountsUrl}/oauth/v2/auth?${q}`;}
  async exchangeAuthorizationCode(c:OAuthConfig,code:string,extra:Record<string,string>={}){const accounts=extra.accountsUrl??this.accountsUrl;const form=new URLSearchParams({grant_type:'authorization_code',client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,code});const b=await fetchJson<any>(`${accounts}/oauth/v2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});return this.token(b,accounts);}
  async refreshToken(c:OAuthConfig,t:TokenSet){if(!t.refreshToken)throw new Error('Zoho refresh token missing');const accounts=String(t.accountsUrl??this.accountsUrl);const form=new URLSearchParams({grant_type:'refresh_token',client_id:c.clientId,client_secret:c.clientSecret,refresh_token:t.refreshToken});const b=await fetchJson<any>(`${accounts}/oauth/v2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});return {...t,...this.token(b,accounts),refreshToken:t.refreshToken};}
  private token(b:any,accountsUrl:string):TokenSet{return {accessToken:b.access_token,refreshToken:b.refresh_token,tokenType:b.token_type??'Bearer',scope:b.scope,apiDomain:b.api_domain??this.apiDomain,accountsUrl,expiresAt:Date.now()+Number(b.expires_in??3600)*1000};}
  private base(ctx:ProviderRequestContext){return `${String(ctx.credentials.apiDomain??ctx.connectionConfig.apiDomain??this.apiDomain)}/crm/v8`;}
  private headers(ctx:ProviderRequestContext,extra:Record<string,string>={}){return {authorization:`Zoho-oauthtoken ${ctx.credentials.accessToken}`,'content-type':'application/json',...extra};}
  async discoverObjects(ctx:ProviderRequestContext){const b=await fetchJson<any>(`${this.base(ctx)}/settings/modules`,{headers:this.headers(ctx)});return (b.modules??[]).filter((m:any)=>m.api_supported).map((m:any)=>({name:m.api_name,label:m.module_name,fields:[]} satisfies ObjectSchema));}
  async discoverFields(ctx:ProviderRequestContext,object:string){assertIdentifier(object);const b=await fetchJson<any>(`${this.base(ctx)}/settings/fields?module=${encodeURIComponent(object)}`,{headers:this.headers(ctx)});return (b.fields??[]).map((f:any)=>({name:f.api_name,label:f.field_label,type:f.data_type,readable:true,writable:!f.read_only,required:!!f.system_mandatory,unique:!!f.unique?.casesensitive} satisfies FieldSchema));}
  async getRecord(ctx:ProviderRequestContext,object:string,id:string,fields?:string[]){assertIdentifier(object);const q=fields?.length?`?fields=${encodeURIComponent(fields.join(','))}`:'';const b=await fetchJson<any>(`${this.base(ctx)}/${object}/${encodeURIComponent(id)}${q}`,{headers:this.headers(ctx)});const row=b.data?.[0];if(!row)throw new Error('Zoho record not found');return this.remote(object,row);}
  async listRecords(ctx:ProviderRequestContext,object:string,options:ListOptions={}):Promise<ListPage>{assertIdentifier(object);const q=new URLSearchParams({per_page:String(Math.min(options.limit??200,200))});if(options.cursor)q.set('page_token',options.cursor);if(options.fields?.length)q.set('fields',options.fields.join(','));const extra:Record<string,string>={};if(options.modifiedSince)extra['If-Modified-Since']=options.modifiedSince;const res=await fetch(`${this.base(ctx)}/${object}?${q}`,{headers:this.headers(ctx,extra)});if(res.status===304)return {records:[],watermark:new Date().toISOString()};const text=await res.text();if(!res.ok)throw new Error(`Zoho list failed ${res.status}: ${text}`);const b=text?JSON.parse(text):{};return {records:(b.data??[]).map((r:any)=>this.remote(object,r)),nextCursor:b.info?.more_records?b.info?.next_page_token:undefined,watermark:new Date().toISOString()};}
  async createRecord(ctx:ProviderRequestContext,object:string,data:Record<string,unknown>){assertIdentifier(object);const b=await fetchJson<any>(`${this.base(ctx)}/${object}`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify({data:[data]})});const id=b.data?.[0]?.details?.id;if(!id)throw new Error(`Zoho create failed: ${JSON.stringify(b)}`);return this.getRecord(ctx,object,id,Object.keys(data));}
  async updateRecord(ctx:ProviderRequestContext,object:string,id:string,data:Record<string,unknown>){assertIdentifier(object);const b=await fetchJson<any>(`${this.base(ctx)}/${object}/${encodeURIComponent(id)}`,{method:'PUT',headers:this.headers(ctx),body:JSON.stringify({data:[data]})});if(!b.data?.[0]?.details?.id)throw new Error(`Zoho update failed: ${JSON.stringify(b)}`);return this.getRecord(ctx,object,id,Object.keys(data));}
  async upsertRecord(ctx:ProviderRequestContext,object:string,key:{field:string;value:string},data:Record<string,unknown>){assertIdentifier(object);assertIdentifier(key.field);const body={data:[{...data,[key.field]:key.value}],duplicate_check_fields:[key.field]};const b=await fetchJson<any>(`${this.base(ctx)}/${object}/upsert`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify(body)});const id=b.data?.[0]?.details?.id;if(!id)throw new Error(`Zoho upsert failed: ${JSON.stringify(b)}`);return this.getRecord(ctx,object,id,Object.keys(data));}
  async deleteRecord(ctx:ProviderRequestContext,object:string,id:string){const res=await fetch(`${this.base(ctx)}/${assertIdentifier(object)}/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers(ctx)});if(!res.ok&&res.status!==404)throw new Error(`Zoho delete failed: ${res.status}`);}
  normalize(object:string,remote:RemoteRecord,mapping:EntitySyncConfig){return genericNormalize(object,remote,mapping);}
  denormalize(object:string,canonical:any,mapping:EntitySyncConfig){return genericDenormalize(object,canonical,mapping);}
  async parseWebhook(payload:unknown):Promise<ProviderWebhookEvent[]>{const p:any=payload??{};const module=String(p.module??p.module_api_name??p.module_name??'Contacts');const ids:Array<string>=Array.isArray(p.ids)?p.ids.map(String):p.id?[String(p.id)]:[];const op=String(p.operation??p.operation_type??'update').toLowerCase();const operation=op.includes('delete')?'delete':op.includes('insert')?'create':'update';return ids.map(id=>({id:String(p.channel_id??p.channelId??'zoho')+':'+id+':'+String(p.token??p.event_time??Date.now()),object:module,remoteId:id,operation,occurredAt:p.event_time?new Date(p.event_time).toISOString():undefined,payload:p}));}
  private remote(object:string,row:any):RemoteRecord{const fields={...row};const id=String(fields.id);delete fields.id;return {id,object,fields,createdAt:row.Created_Time,updatedAt:row.Modified_Time,raw:row};}
}
