import type { CRMProvider, EntitySyncConfig, FieldSchema, ListOptions, ListPage, OAuthConfig, ObjectSchema, ProviderRequestContext, RemoteRecord, TokenSet } from '@sales-connect/types';
import { assertIdentifier, fetchJson, genericDenormalize, genericNormalize } from '@sales-connect/provider-common';

export interface SalesforceProviderOptions { loginUrl?: string; apiVersion?: string }
export class SalesforceProvider implements CRMProvider {
  id='salesforce' as const;
  private loginUrl:string; private apiVersion:string;
  constructor(options:SalesforceProviderOptions={}){ this.loginUrl=options.loginUrl??'https://login.salesforce.com'; this.apiVersion=options.apiVersion??'v64.0'; }
  capabilities(){ return {webhooks:false,cdc:true,upsert:true,externalIds:true,customObjects:true,batchWrite:true,bulkRead:true}; }
  getAuthorizationUrl(c:OAuthConfig,state:string,scopes=['api','refresh_token']){ const q=new URLSearchParams({response_type:'code',client_id:c.clientId,redirect_uri:c.redirectUri,state,scope:scopes.join(' ')}); return `${this.loginUrl}/services/oauth2/authorize?${q}`; }
  async exchangeAuthorizationCode(c:OAuthConfig,code:string){ const form=new URLSearchParams({grant_type:'authorization_code',client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,code}); const body=await fetchJson<any>(`${this.loginUrl}/services/oauth2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}); return this.token(body); }
  async refreshToken(c:OAuthConfig,t:TokenSet){ if(!t.refreshToken) throw new Error('Salesforce refresh token missing'); const form=new URLSearchParams({grant_type:'refresh_token',client_id:c.clientId,client_secret:c.clientSecret,refresh_token:t.refreshToken}); const body=await fetchJson<any>(`${this.loginUrl}/services/oauth2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}); return {...t,...this.token(body),refreshToken:t.refreshToken}; }
  private token(b:any):TokenSet { return {accessToken:b.access_token,refreshToken:b.refresh_token,instanceUrl:b.instance_url,tokenType:b.token_type??'Bearer',scope:b.scope,expiresAt:Date.now()+10*60*1000,id:b.id}; }
  private base(ctx:ProviderRequestContext){ const instance=String(ctx.credentials.instanceUrl??ctx.connectionConfig.instanceUrl??''); if(!instance) throw new Error('Salesforce instanceUrl missing'); return `${instance}/services/data/${this.apiVersion}`; }
  private headers(ctx:ProviderRequestContext){ return {authorization:`Bearer ${ctx.credentials.accessToken}`,'content-type':'application/json'}; }
  async discoverObjects(ctx:ProviderRequestContext){ const b=await fetchJson<any>(`${this.base(ctx)}/sobjects`,{headers:this.headers(ctx)}); return (b.sobjects??[]).filter((o:any)=>o.queryable).map((o:any)=>({name:o.name,label:o.label,fields:[]} satisfies ObjectSchema)); }
  async discoverFields(ctx:ProviderRequestContext,object:string){ assertIdentifier(object); const b=await fetchJson<any>(`${this.base(ctx)}/sobjects/${object}/describe`,{headers:this.headers(ctx)}); return (b.fields??[]).map((f:any)=>({name:f.name,label:f.label,type:f.type,readable:true,writable:f.updateable||f.createable,required:!f.nillable,unique:f.unique} satisfies FieldSchema)); }
  async getRecord(ctx:ProviderRequestContext,object:string,id:string,fields?:string[]){ assertIdentifier(object); const q=fields?.length?`?fields=${encodeURIComponent(['Id','CreatedDate','SystemModstamp',...fields].join(','))}`:''; const b=await fetchJson<any>(`${this.base(ctx)}/sobjects/${object}/${encodeURIComponent(id)}${q}`,{headers:this.headers(ctx)}); return this.remote(object,b); }
  async listRecords(ctx:ProviderRequestContext,object:string,options:ListOptions={}):Promise<ListPage>{
    assertIdentifier(object); let b:any;
    if(options.cursor){ const url=options.cursor.startsWith('http')?options.cursor:`${String(ctx.credentials.instanceUrl)}${options.cursor}`; b=await fetchJson<any>(url,{headers:this.headers(ctx)}); }
    else { const fields=['Id','CreatedDate','SystemModstamp',...(options.fields??[])].map(assertIdentifier); const where=options.modifiedSince?` WHERE SystemModstamp >= ${options.modifiedSince}`:''; const soql=`SELECT ${[...new Set(fields)].join(',')} FROM ${object}${where} ORDER BY SystemModstamp ASC LIMIT ${Math.min(options.limit??200,2000)}`; b=await fetchJson<any>(`${this.base(ctx)}/query?q=${encodeURIComponent(soql)}`,{headers:this.headers(ctx)}); }
    return {records:(b.records??[]).map((r:any)=>this.remote(object,r)),nextCursor:b.done?undefined:b.nextRecordsUrl,watermark:new Date().toISOString()};
  }
  async createRecord(ctx:ProviderRequestContext,object:string,data:Record<string,unknown>){ assertIdentifier(object); const b=await fetchJson<any>(`${this.base(ctx)}/sobjects/${object}`,{method:'POST',headers:this.headers(ctx),body:JSON.stringify(data)}); return await this.getRecord(ctx,object,b.id); }
  async updateRecord(ctx:ProviderRequestContext,object:string,id:string,data:Record<string,unknown>){ assertIdentifier(object); await fetchJson<any>(`${this.base(ctx)}/sobjects/${object}/${encodeURIComponent(id)}`,{method:'PATCH',headers:this.headers(ctx),body:JSON.stringify(data)}); return await this.getRecord(ctx,object,id,Object.keys(data)); }
  async upsertRecord(ctx:ProviderRequestContext,object:string,key:{field:string;value:string},data:Record<string,unknown>){ assertIdentifier(object);assertIdentifier(key.field); const url=`${this.base(ctx)}/sobjects/${object}/${key.field}/${encodeURIComponent(key.value)}`; const res=await fetch(url,{method:'PATCH',headers:this.headers(ctx),body:JSON.stringify(data)}); if(!res.ok) throw new Error(`Salesforce upsert failed: ${res.status} ${await res.text()}`); const text=await res.text(); if(text){const body=JSON.parse(text); if(body.id)return this.getRecord(ctx,object,body.id,Object.keys(data));} const found=await fetchJson<any>(url,{headers:this.headers(ctx)}); return this.remote(object,found); }
  async deleteRecord(ctx:ProviderRequestContext,object:string,id:string){ const res=await fetch(`${this.base(ctx)}/sobjects/${assertIdentifier(object)}/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers(ctx)}); if(!res.ok&&res.status!==404) throw new Error(`Salesforce delete failed: ${res.status}`); }
  normalize(object:string,remote:RemoteRecord,mapping:EntitySyncConfig){ return genericNormalize(object,remote,mapping); }
  denormalize(object:string,canonical:any,mapping:EntitySyncConfig){ return genericDenormalize(object,canonical,mapping); }
  private remote(object:string,b:any):RemoteRecord { const fields={...b}; delete fields.attributes; delete fields.Id; return {id:b.Id,object,fields,createdAt:b.CreatedDate,updatedAt:b.SystemModstamp??b.LastModifiedDate,raw:b}; }
}
