'use client';
import {FormEvent,useEffect,useState} from 'react';
type RecordT={id:string;fields:Record<string,unknown>;updatedAt?:string};
const api=async(path:string,init?:RequestInit)=>{const r=await fetch(`/api/sc/${path}`,{...init,headers:{'content-type':'application/json'}});const b=await r.json();if(!r.ok)throw new Error(b.message??'failed');return b};
export default function Demo(){const [connectionId,setConnectionId]=useState('');const [records,setRecords]=useState<RecordT[]>([]);const [firstName,setFirstName]=useState('Ada');const [lastName,setLastName]=useState('Lovelace');const [email,setEmail]=useState('ada@example.com');const [msg,setMsg]=useState('');
async function loadConnections(){const x=await api('connections');const active=x.connections.find((c:any)=>c.status==='active');if(active)setConnectionId(active.id)}
async function loadRecords(id=connectionId){if(!id)return;const x=await api(`connections/${id}/records/contact`);setRecords(x.records)}
useEffect(()=>{void loadConnections()},[]);useEffect(()=>{if(connectionId)void loadRecords(connectionId)},[connectionId]);
async function submit(e:FormEvent){e.preventDefault();setMsg('Sync event queued');await api(`connections/${connectionId}/records/contact`,{method:'POST',body:JSON.stringify({fields:{firstName,lastName,email}})});await loadRecords()}
return <main><div className="hero"><span>LIVE BIDIRECTIONAL DEMO</span><h1>Your app ⇄ CRM</h1><p>Create a local contact. Sales-Connect maps and pushes it to the connected CRM, then remote changes flow back through webhooks or reconciliation.</p></div><section><label>Active connection ID</label><input value={connectionId} onChange={e=>setConnectionId(e.target.value)} placeholder="con_..."/><button onClick={()=>void loadRecords()}>Load records</button></section><section><h2>Create contact</h2><form onSubmit={submit}><input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="First name"/><input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Last name"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><button disabled={!connectionId}>Create + sync</button></form>{msg&&<p className="ok">{msg}</p>}</section><section><h2>Local synchronized records</h2><div className="records">{records.map(r=><article key={r.id}><b>{String(r.fields.firstName??'')} {String(r.fields.lastName??'')}</b><p>{String(r.fields.email??'')}</p><small>{r.id}</small></article>)}</div></section></main>}
